name: Docker Image Vulnability Check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag local/aria-ui:latest
    - name: Scan image
      uses: anchore/scan-action@master
      with:
        image-reference: "local/aria-ui:latest"
        dockerfile-path: "./Dockerfile"
        fail-build: true
